version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"     # RabbitMQ (AMQP)
      - "15672:15672"   # RabbitMQ Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 30s
      timeout: 10s
      retries: 5

  inventory-api:
    build:
      context: .
      dockerfile: Inventory.Api/Dockerfile
    ports:
      - "5001:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./data:/app/data:rw
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/inventory.db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  inventory-worker:
    build:
      context: .
      dockerfile: Inventory.Worker/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./data:/app/data:rw
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/inventory.db

networks:
  inventory-network:
    driver: bridge